# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  run-server:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          KEY: ${{ secrets.SSH_KEY }}
          script: |
            # Stop running container
            git clone https://github.com/ttruty/Codememes.git
            cd Codememes
            
            # stop all running containers
            docker stop $(docker ps -aq) 
            #remove all containers
            docker rm $(docker ps -aq)
            #remove all images
            docker rmi $(docker images -q)
            
            #build container
            docker build -t codememes-image:latest .
            # run container
            docker run -d -p 3000:9091 ttruty/codememes-image

          
          
    # Steps represent a s
